### ISSUE TITLE
Баг квеста, баг меню.

### ISSUE THREAD

**Issue by OdinWish** [SoulderCommunity/Technical-Department#11]
![Screenshot_123](https://user-images.githubusercontent.com/105158808/201917136-41697450-f518-46ac-a3ff-56a8cb269f90.png)
![Screenshot_124](https://user-images.githubusercontent.com/105158808/201917146-197fb32e-2ba3-4f90-ae63-742cfa7c3626.png)
https://www.youtube.com/watch?v=5EufxLlnL8k

**Comment by SoulderCommunity** [comment]
Здравствуйте, баг меню к сожалению на данный момент нет возможности исправить. Возможно у него либо экран не 16:9, либо он вы играете не в полноэкранном режиме. Квест вам не выдаётся, т.к Шизу это не полноценный квестовый персонаж, он создан лишь для информирования игроков о системе игры. На данный момент квесты у нас добавляются лишь временные преуроченные к каким-либо праздникам.
