### ISSUE TITLE
Баги

### ISSUE THREAD

**Issue by Evtril** [SoulderCommunity/Technical-Department#6]
_**В банке можно готовить в обменнике**_ 

![image](https://user-images.githubusercontent.com/96728789/200441759-b8b48d49-dca9-4381-9bd7-c518e95e1ee5.png)

![image](https://user-images.githubusercontent.com/96728789/200441737-551eb770-c48a-4b60-82e4-2b6ff97aefa1.png)

![image](https://user-images.githubusercontent.com/96728789/200441718-335d3f55-ffb2-42a8-bd31-dffe20caae59.png)

**Comment by SoulderCommunity** [comment]
Спасибо за найденный баг. Исправили.
